services:
  postgres:
    container_name: postgres_app
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data
    ports:
      - "5432:5432"
